About page
BYTE-ADMU/startup-summit pull request #1
Opened 2021-01-12 07:26 UTC by GDivino

- [X] Desktop view
- [ ] Tablet view
- [ ] Mobile view
- [ ] Complete photos

Note:
- Changed app.vue for testing purposes

2021-01-12 15:55 UTC, GDivino commented
- [X] Desktop view

- [X] Tablet view

- [X] Mobile view

Notes:
- Changed App.vue for testing purposes
- Changed the pixel units to vw and vh units
- Applied flex box to the code to make it responsive

2021-01-17 04:09 UTC, GDivino commented
From screen 1410px - 1025px, the text goes past the image
![image](https://user-images.githubusercontent.com/68019100/104830759-c3fa7880-58bc-11eb-8156-0ccc0a06fe5c.png)

2021-01-17 04:31 UTC, GDivino commented
Relevant screenshots
- Desktop view:
![image](https://user-images.githubusercontent.com/68019100/104830963-0329c900-58bf-11eb-8250-8c8b8c444e3c.png)
- Tablet view:
![image](https://user-images.githubusercontent.com/68019100/104831027-bc889e80-58bf-11eb-954b-e3f43ff5bf6a.png)
- Mobile view:
![image](https://user-images.githubusercontent.com/68019100/104831043-f9ed2c00-58bf-11eb-8d9d-b5a32eabcbd1.png)

2021-01-21 19:25 UTC, Znarfois approved these changes
Looks great!

2021-01-27 09:08 UTC, Znarfois commented
The video is bigger than what we expect when ran. Please check if it is overwritten in another part of the code

2021-01-31 18:33 UTC, Znarfois requested changes
Just small things, other than that looks great! Good job @GDivino

2021-01-31 18:33 UTC, Znarfois commented on public/index.html
> +<html lang="en" style="max-width: 100%; overflow-x: hidden;">
Can we move this to CSS?

2021-01-31 18:33 UTC, Znarfois commented on public/index.html
> +  <body style="margin: 0;">
Move this to CSS as well

2021-01-31 18:33 UTC, Znarfois commented on src/components/About.vue
> +                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer too
Bump design team if this is available na

2021-02-01 11:30 UTC, Znarfois approved these changes

2021-02-04 10:20 UTC, merged