Finished responsiveness
BYTE-ADMU/startup-summit pull request #4
Opened 2021-01-12 19:33 UTC by GDivino

- [X]  Desktop view

- [X]  Tablet view

- [X] Mobile view

Notes
- Changed App.vue for testing purposes
- Created a temporary button while there's no button component yet.

2021-01-17 04:48 UTC, GDivino commented
Relevant screenshots:
- Desktop view:
![image](https://user-images.githubusercontent.com/68019100/104831242-070b1a80-58c2-11eb-861d-755f33d722c0.png)
- Tablet view:
![image](https://user-images.githubusercontent.com/68019100/104831255-1e4a0800-58c2-11eb-9656-1bf21b82a31a.png)
- Mobile view:
![image](https://user-images.githubusercontent.com/68019100/104831273-4d607980-58c2-11eb-8d34-bd5818c63b3f.png)

2021-01-21 19:39 UTC, Znarfois requested changes
Address the comments nalang, then we can merge!

2021-01-21 19:39 UTC, Znarfois commented on src/components/Home/WhatIsSus.vue
> +            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a
We need to fill this nalang with the actual content before we merge.

2021-01-21 19:39 UTC, Znarfois commented on src/components/Home/WhatIsSus.vue
> +            <button class="learn-more" type="button">Learn more</button>
Replace with the button from Clarz

2021-01-21 19:39 UTC, Znarfois commented on src/components/Home/WhatIsSus.vue
> +        <div class="picture"></div>
Let's add the picture first before merging. Make sure to add an alt = "something"

2021-02-04 11:13 UTC, closed without merging